# Generated by Django 6.1 on 2026-08-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='model',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='Persons',
            new_name='people',
        ),
    ]
