# Generated by Django 6.1 on 2026-08-17 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_person_options_rename_model_pet_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['is_adopted', 'name']},
        ),
        migrations.AddField(
            model_name='pet',
            name='age_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='pets/default.jpg', upload_to='pets/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='story',
            field=models.TextField(blank=True, help_text='Rescue story and character description'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='active_need',
            field=models.IntegerField(help_text='Activity level from 1 to 10'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='favorite_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
