# Generated by Django 6.1 on 2026-08-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_pet_options_pet_age_months_pet_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('UT', 'Under Treatment / In Shelter'), ('RA', 'Ready for Adoption'), ('AD', 'Adopted')], default='UT', help_text='Current status of the pet', max_length=2),
        ),
    ]
