# Generated by Django 6.1 on 2026-08-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_pet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='people',
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
    ]
