# Generated by Django 6.1 on 2026-08-17 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_pet_people_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
