# Generated by Django 6.1 on 2026-08-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_pet_people'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
    ]
