# Generated by Django 6.1 on 2026-08-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_pet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['is_adopted', 'name']},
        ),
    ]
