# Generated by Django 6.1 on 2026-08-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_pet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='people',
            new_name='visitors',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_adopted',
        ),
    ]
