# Generated by Django 6.1 on 2026-08-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_pet_options_rename_people_pet_visitors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
