# Generated by Django 6.1 on 2026-08-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='active_need',
            field=models.IntegerField(blank=True, help_text='Activity level from 1 to 10', null=True),
        ),
    ]
