# Generated by Django 6.1 on 2026-08-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_breed_active_need'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='about_user',
        ),
    ]
