# Generated by Django 6.0.8 on 2026-08-21 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_person_about_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='active_need',
            field=models.IntegerField(blank=True, help_text='Activity level from 1 to 10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
